# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Concept-bases XAI Tutorial
email: gesina.schwalbe@uni-luebeck.de
description: >- # this means to ignore newlines until "baseurl:"
  Webpage of the tutorial Explaining Vision and Language Models: A Concept-Based Approach at ECAI 2025
author: Gesina Schwalbe
github_username:  gesina

domain: gesina.github.io        # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://gesina.github.io   # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /c-xai-tutorial        # place folder name if the site is served in a subfolder

# Build settings
theme: minima
plugins:
#  - jekyll-feed
  - jekyll-seo-tag
provide_feed: false

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- index.md
- organizers.md
- schedule.md
- contactus.md
- material.md

# # Specify the name of a file to show as a masthead graphic at the top of each page, instead of a title, here:
# masthead: assets/img/banner.jpg
# # Description (alt text) for the masthead
# masthead_description: Adapted from Machine Learning & Artificial Intelligence by mikemacmarketing; licensed under CC BY 2.0

# A two-line attribution (remove this if you have to, but we'd appreciate if you leave this as is)
attribution: >
  Based on the <a href="https://github.com/krrish94/sniffle-workshop">sniffle-workshop</a> Template.

# Displays a "last updated" date in the footer if set to "true"
last_updated: true

# Define collections (speakers, organizers, papers)
# To turn off any of these collections, just set "output" to "false"
collections:
  speakers:
    output: false
  organizers:
    output: true
  schedule:
    sort_by: sequence_id
    output: true
  papers:
    sort_by: sequence_id
    output: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
